spring:
  application:
    name: enterprise-rag
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/enterprise_rag}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate

  ai:
    model:
      chat: openai
      embedding: ollama

    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: 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
      chat:
        options:
          model: dots-studio/dots-3-note-preview:free
          temperature: 0.5


    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

logging:
  level:
    com.openai: info
    com.openai.core: info
    org.springframework.ai.openai: info

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
confluence:
  base-url: https://gmservices033.atlassian.net/wiki
  email: gmservices033@gmail.com
  api-token: ATATT3xFfGF0IUZhRhvr6ZY89Tgua5df3rog4mZedxG2-lGfCQL9u5jF8fTvT4S6BAXzTWUVo_33aYvmQHyl8JlNY4neGCZZfGWoLDklZwMvQSJ5Mfeod5h4b8HQx9pSYI-Hb4e48CNQc6GnXqzcBv8qTdC8k604ee6inoXGEIBZpYHUpxi-Nhc=B4D7D9A9
rag:
  pipeline:
    chunking: TokenTextSplitter
    embedding-model: nomic-embed-text
    vector-store: pgvector
    generation-provider: OpenRouter

openrouter:
  base-url: https://openrouter.ai/api/v1
  api-key: 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

jwt:
  secret: K8vQ2mX7pL9sN4zR6tY1wF3hJ5cD0aB8uG2xV7nM9qP4sT6k
  expiration: 86400000

conversation:
  history:
    max-messages: 15